window.productosData = [
  { sku: "ADAPTADOR-POE", nombre: "Adaptador PoE", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=ADAPTADOR+POE" },
  { sku: "ADAPTADOR-REPUESTO-CAMARA", nombre: "Adaptador Repuesto Cámara", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=ADAPTADOR+REPUESTO+CAMARA" },
  { sku: "AURORA TITAN PRO - 6MP", nombre: "Aurora Titan PRO 6MP", precio: 0, imagen: "imagenes/Largo Alcance/Titan pro.jpg" },
  { sku: "BRAZO-100CM", nombre: "Brazo 100cm", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=BRAZO+100CM" },
  { sku: "BRAZO-120CM", nombre: "Brazo 120cm", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=BRAZO+120CM" },
  { sku: "BRAZO-50CM", nombre: "Brazo 50cm", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=BRAZO+50CM" },
  { sku: "BRAZO-60CM", nombre: "Brazo 60cm", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=BRAZO+60CM" },
  { sku: "CABLE-RED-10M", nombre: "Cable Red 10M", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CABLE+RED+10M" },
  { sku: "CABLE-RED-15M", nombre: "Cable Red 15M", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CABLE+RED+15M" },
  { sku: "CAMARA-CCTV-SIMULADA", nombre: "Cámara CCTV Simulada", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMARA+CCTV+SIMULADA" },
  { sku: "CAMARA-ESPIA-A9", nombre: "Cámara Espía A9", precio: 0, imagen: "imagenes/Basicas Interiores/MINI ESPÍA.jpg" },
  { sku: "CAMARA-FOCO", nombre: "Cámara Foco", precio: 0, imagen: "imagenes/Basicas Interiores/Cámara Foco.jpg" },
  { sku: "CAMARA-FOCO-DOBLE", nombre: "Cámara Foco Doble", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMARA+FOCO+DOBLE" },
  { sku: "CAMARA-FOCO-IC008B", nombre: "Cámara Foco IC008B", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMARA+FOCO+IC008B" },
  { sku: "CAMARA-FOCO-TRIPLE", nombre: "Cámara Foco Triple", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMARA+FOCO+TRIPLE" },
  { sku: "CAMARA-SOLAR", nombre: "Cámara Solar", precio: 0, imagen: "imagenes/Chip Solar/A31 solar.jpg" },
  { sku: "CAM-AUTO-RETROVISOR", nombre: "Cámara Auto Retrovisor", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAM+AUTO+RETROVISOR" },
  { sku: "CAMIP-29Y", nombre: "Cámara IP 29Y", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+29Y" },
  { sku: "CAMIP-4-LENTES-859B", nombre: "Cámara IP 4 Lentes 859B", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+4+LENTES+859B" },
  { sku: "CAMIP-A10", nombre: "Cámara IP A10", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+A10" },
  { sku: "CAMIP-A28B", nombre: "Cámara IP A28B", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+A28B" },
  { sku: "CAMIP-A31", nombre: "Cámara IP A31", precio: 0, imagen: "imagenes/Basicas Exteriores/A31.jpg" },
  { sku: "CAMIP-A32", nombre: "Cámara IP A32", precio: 0, imagen: "imagenes/Basicas Exteriores/A32.jpg" },
  { sku: "CAMIP-A8", nombre: "Cámara IP A8", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+A8" },
  { sku: "CAMIP-CHIP-538GL-15X", nombre: "Cámara IP Chip 538GL 15X", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+538GL+15X" },
  { sku: "CAMIP-CHIP-Q69", nombre: "Cámara IP Chip Q69", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+Q69" },
  { sku: "CAMIP-CHIP-S12", nombre: "Cámara IP Chip S12", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+S12" },
  { sku: "CAMIP-CHIP-S60", nombre: "Cámara IP Chip S60", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+S60" },
  { sku: "CAMIP-CHIP-SD320", nombre: "Cámara IP Chip SD320", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+SD320" },
  { sku: "CAMIP-CHIP-ST63", nombre: "Cámara IP Chip ST63", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+ST63" },
  { sku: "CAMIP-CHIP-T6", nombre: "Cámara IP Chip T6", precio: 0, imagen: "imagenes/Chip Solar/SOLAR CHIP T6.jpg" },
  { sku: "CAMIP-CHIP-TQ5", nombre: "Cámara IP Chip TQ5", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+CHIP+TQ5" },
  { sku: "CAMIP-CHIP-Y5-4K", nombre: "Cámara IP Chip Y5 4K", precio: 0, imagen: "imagenes/Chip Solar/CHIP Y5.jpg" },
  { sku: "CAMIP-ESPIA-4G", nombre: "Cámara IP Espía 4G", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+ESPIA+4G" },
  { sku: "CAMIP-EXTERIOR", nombre: "Cámara IP Exterior", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+EXTERIOR" },
  { sku: "CAMIP-EXTERIOR DOMO", nombre: "Cámara IP Exterior Domo", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+EXTERIOR+DOMO" },
  { sku: "CAMIP-INTERIOR", nombre: "Cámara IP Interior", precio: 0, imagen: "imagenes/Basicas Interiores/Cámara interior.jpg" },
  { sku: "CAMIP-INTERIOR-DOBLE", nombre: "Cámara IP Interior Doble", precio: 0, imagen: "imagenes/Basicas Interiores/Interior Dual.jpg" },
  { sku: "CAMIP-PANORAMICA-Y6", nombre: "Cámara IP Panorámica Y6", precio: 0, imagen: "imagenes/Solar Wi-Fi/SOLAR Y6.jpg" },
  { sku: "CAMIP-PULPO", nombre: "Cámara IP Pulpo", precio: 0, imagen: "imagenes/Largo Alcance/Cámara Pulpo.jpg" },
  { sku: "CAMIP-PULPO-2", nombre: "Cámara IP Pulpo 2", precio: 0, imagen: "imagenes/Basicas Exteriores/PULPO DIGITAL.jpg" },
  { sku: "CAMIP-PULPO-5-LENTES", nombre: "Cámara IP Pulpo 5 Lentes", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+PULPO+5+LENTES" },
  { sku: "CAMIP-PULPO-6-LENTES-ZOOM", nombre: "Cámara IP Pulpo 6 Lentes Zoom", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+PULPO+6+LENTES+ZOOM" },
  { sku: "CAMIP-PULPO-SOLAR", nombre: "Cámara IP Pulpo Solar", precio: 0, imagen: "imagenes/Solar Wi-Fi/PULPO SOLAR.jpg" },
  { sku: "CAMIP-QQ9", nombre: "Cámara IP QQ9", precio: 0, imagen: "imagenes/Largo Alcance/QQ9.jpg" },
  { sku: "CAMIP-SOLAR-2-PANELES", nombre: "Cámara IP Solar 2 Paneles", precio: 0, imagen: "imagenes/Solar Wi-Fi/SOLAR DOBLE PANEL.jpg" },
  { sku: "CAMIP-SOLAR-DOBLE-VCS093", nombre: "Cámara IP Solar Doble VCS093", precio: 0, imagen: "imagenes/Solar Wi-Fi/Exterior solar Dual.jpg" },
  { sku: "CAMIP-T6", nombre: "Cámara IP T6", precio: 0, imagen: "imagenes/Largo Alcance/Cámara T6.jpg" },
  { sku: "CAMIP-VIDEOLLAMADA", nombre: "Cámara IP Videollamada", precio: 0, imagen: "imagenes/Basicas Interiores/Cámara Pantalla.jpg" },
  { sku: "CAMIP-WIFI-Q69", nombre: "Cámara IP WiFi Q69", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=CAMIP+WIFI+Q69" },
  { sku: "CAMIP-XM-A6-MINI", nombre: "Cámara IP XM A6 Mini", precio: 0, imagen: "imagenes/Basicas Exteriores/A6.jpg" },
  { sku: "CRUISER AURORA - 4MP", nombre: "Cruiser Aurora 4MP", precio: 0, imagen: "imagenes/Imou/AURORA.jpg" },
  { sku: "CRUISER CHIP - AOV PT", nombre: "Cruiser Chip AOV PT", precio: 0, imagen: "imagenes/Imou/Cruiser AOV PT.jpg.jpeg" },
  { sku: "CRUISER DUAL - 5MP", nombre: "Cruiser Dual 5MP", precio: 0, imagen: "imagenes/Imou/CRUISER DUAL.jpg" },
  { sku: "CRUISER PANO Z - 13MP", nombre: "Cruiser Pano Z 13MP", precio: 0, imagen: "imagenes/Imou/CRUISER PANO Z.jpg.jpeg" },
  { sku: "CRUISER SC - 5MP", nombre: "Cruiser SC 5MP", precio: 0, imagen: "imagenes/Imou/CRUISER SC 5MP.jpg" },
  { sku: "CRUISER SC - 8MP", nombre: "Cruiser SC 8MP", precio: 0, imagen: "imagenes/Imou/CRUISER SC.jpg" },
  { sku: "CRUISER TRIPLE - 5MP", nombre: "Cruiser Triple 5MP", precio: 0, imagen: "imagenes/Imou/CRUISER TRIPLE.jpg" },
  { sku: "CRUISER Z - 5MP", nombre: "Cruiser Z 5MP", precio: 0, imagen: "imagenes/Imou/CRUISER Z.jpg" },
  { sku: "ESTANTE-BEBE-5", nombre: "Estante Bebé 5", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=ESTANTE+BEBE+5" },
  { sku: "FOCO IMOU - 5MP", nombre: "Foco Imou 5MP", precio: 0, imagen: "imagenes/Imou/BULB CAM.jpg" },
  { sku: "MEMORIA-128GB", nombre: "Memoria 128GB", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=MEMORIA+128GB" },
  { sku: "MEMORIA-256GB", nombre: "Memoria 256GB", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=MEMORIA+256GB" },
  { sku: "MEMORIA-64GB", nombre: "Memoria 64GB", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=MEMORIA+64GB" },
  { sku: "NVR-10C-IMOU", nombre: "NVR 10C Imou", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=NVR+10C+IMOU" },
  { sku: "NVR-HIKVISION", nombre: "NVR Hikvision", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=NVR+HIKVISION" },
  { sku: "OPALUX-ALARMA-CONTROL-58C", nombre: "Opalux Alarma Control 58C", precio: 0, imagen: "imagenes/Tapo/SIRENA COMUNITARIA.jpg.jpeg" },
  { sku: "PANEL-SOLAR-300W", nombre: "Panel Solar 300W", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=PANEL+SOLAR+300W" },
  { sku: "RANGER 2 - 5MP", nombre: "Ranger 2 5MP", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=RANGER+2+5MP" },
  { sku: "RANGER 2 PRO - 4K", nombre: "Ranger 2 PRO 4K", precio: 0, imagen: "imagenes/Imou/RANGER 2 PRO 4K.jpg.jpeg" },
  { sku: "RANGER 2 PRO - 5MP", nombre: "Ranger 2 PRO 5MP", precio: 0, imagen: "imagenes/Imou/RANGER 2 PRO.jpg" },
  { sku: "RANGER DUAL LENS - 5MP", nombre: "Ranger Dual Lens 5MP", precio: 0, imagen: "imagenes/Imou/RANGER 2 DUAL.jpg" },
  { sku: "RANGER MINI - 5MP", nombre: "Ranger Mini 5MP", precio: 0, imagen: "imagenes/Imou/RANGER MINI.jpg" },
  { sku: "RANGER RC - 5MP", nombre: "Ranger RC 5MP", precio: 0, imagen: "https://placehold.co/400x300/1e293b/white?text=RANGER+RC+5MP" },
  { sku: "TAPO-C200 (1080p Blanco)", nombre: "Tapo C200 (1080p Blanco)", precio: 0, imagen: "imagenes/Tapo/TAPO C200.jpg" },
  { sku: "TAPO-C200C (1080p Blanco)", nombre: "Tapo C200C (1080p Blanco)", precio: 0, imagen: "imagenes/Tapo/TAPO C200C.jpg.jpeg" },
  { sku: "TAPO-C201 (1080p Negro)", nombre: "Tapo C201 (1080p Negro)", precio: 0, imagen: "imagenes/Tapo/TAPO C201.jpg" },
  { sku: "TAPO-C210 (2K Blanco)", nombre: "Tapo C210 (2K Blanco)", precio: 0, imagen: "imagenes/Tapo/TAPO C210.jpg" },
  { sku: "TAPO-C211 (2K Negro)", nombre: "Tapo C211 (2K Negro)", precio: 0, imagen: "imagenes/Tapo/TAPO C211.jpg" },
  { sku: "TAPO-C500 (1080p Exterior)", nombre: "Tapo C500 (1080p Exterior)", precio: 0, imagen: "imagenes/Tapo/TAPO C500.jpg" },
  { sku: "TAPO-C520WS (2K Exterior)", nombre: "Tapo C520WS (2K Exterior)", precio: 0, imagen: "imagenes/Tapo/TAPO C520.jpg" },
  { sku: "TAPO-ENCHUFE-P105", nombre: "Tapo Enchufe P105", precio: 0, imagen: "imagenes/Tapo/ENCHUFE INTELIGENTE TAPO.jpg"}
];